# -*- coding: utf-8 -*-
"""
Created on Mon Feb  9 14:37:29 2026

@author: K. Pikounis
"""

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, confusion_matrix
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
import os

# --- CONFIGURATION ---
INPUT_FILE = r"C:\Users\KostasPikounis\OneDrive_Inlecom_Personal\OneDrive - INLECOM\Amfitrite\task2\IWD CNN\dataset_summary_with_splits_from_Server_with_predictions.xlsx"

# Column names generated by the previous script
MODEL_COLS = [
    "pred_res18_scl", 
    "pred_res18_no_scl", 
    "pred_convnext_scl", 
    "pred_rdnet_no_scl"
]

# Ground Truth Column
GT_COL = "indicative_class"
SPLIT_COL = "split"

def analyze_hab_results():
    # 1. Load Data
    print("Loading data...")
    if INPUT_FILE.endswith('.xlsx'):
        df = pd.read_excel(INPUT_FILE)
    else:
        df = pd.read_csv(INPUT_FILE)

    # 2. Prepare Ground Truth (Map to Binary yes/no)
    # Logic: Low -> no, Moderate/High -> yes
    # We assume the predictions are already "yes" / "no" strings
    print("Mapping Ground Truth to Binary (yes/no)...")
    
    def map_gt(val):
        if str(val).lower() == 'low': return 'no'
        return 'yes' # Moderate, High, etc.
    
    df['gt_binary'] = df[GT_COL].apply(map_gt)
    
    # 3. Define splits to analyze
    splits = df[SPLIT_COL].unique()
    
    # --- PART 1: INDIVIDUAL MODEL METRICS ---
    print("\n" + "="*50)
    print("PART 1: PERFORMANCE METRICS PER MODEL")
    print("="*50)
    
    metrics_summary = []

    for split in splits:
        split_df = df[df[SPLIT_COL] == split]
        y_true = split_df['gt_binary']
        
        print(f"\n--- Split: {split.upper()} (n={len(split_df)}) ---")
        
        for model in MODEL_COLS:
            y_pred = split_df[model]
            
            # Calculate Metrics
            # pos_label='yes' ensures F1 is calculated for the Bloom class
            acc = accuracy_score(y_true, y_pred)
            bal_acc = balanced_accuracy_score(y_true, y_pred)
            f1 = f1_score(y_true, y_pred, pos_label='yes')
            
            print(f"{model:<20} | Acc: {acc:.4f} | Bal Acc: {bal_acc:.4f} | F1: {f1:.4f}")
            
            metrics_summary.append({
                "Split": split,
                "Model": model,
                "Accuracy": acc,
                "Balanced_Accuracy": bal_acc,
                "F1_Score": f1
            })

    # Save metrics to CSV for easy charting later
    pd.DataFrame(metrics_summary).to_csv(r"C:\Users\KostasPikounis\OneDrive_Inlecom_Personal\OneDrive - INLECOM\Amfitrite\task2\IWD CNN\metrics_summary.csv", index=False)


    # --- PART 2: PAIRWISE COMPARISON ---
    print("\n" + "="*50)
    print("PART 2: MODEL vs MODEL COMPARISON")
    print("="*50)
    
    # Generate all unique pairs of models
    model_pairs = list(itertools.combinations(MODEL_COLS, 2))
    
    for split in splits:
        split_df = df[df[SPLIT_COL] == split]
        print(f"\n>>> Analyzing Split: {split.upper()} <<<")
        
        for m1, m2 in model_pairs:
            # Vectors for easy comparison
            preds_1 = split_df[m1].values
            preds_2 = split_df[m2].values
            truth = split_df['gt_binary'].values
            
            total = len(split_df)
            
            # A. Agreement
            # Where both models predict the SAME thing (regardless of truth)
            agree_mask = (preds_1 == preds_2)
            agree_count = np.sum(agree_mask)
            agree_pct = (agree_count / total) * 100
            
            # B. Disagreement
            disagree_mask = ~agree_mask
            disagree_count = np.sum(disagree_mask)
            
            print(f"\nComparison: {m1} vs {m2}")
            print(f"  Agreement:    {agree_pct:.1f}% ({agree_count}/{total})")
            
            if disagree_count > 0:
                # Analyze who was right in the disagreements
                # Subset of data where they disagreed
                d_preds_1 = preds_1[disagree_mask]
                d_preds_2 = preds_2[disagree_mask]
                d_truth = truth[disagree_mask]
                
                # M1 Right: M1 matches truth (and since M1!=M2, M2 must be wrong)
                m1_right_count = np.sum(d_preds_1 == d_truth)
                m1_right_pct = (m1_right_count / disagree_count) * 100
                
                # M2 Right: M2 matches truth
                m2_right_count = np.sum(d_preds_2 == d_truth)
                m2_right_pct = (m2_right_count / disagree_count) * 100
                
                print(f"  Disagreement: {disagree_count} cases")
                print(f"    -> {m1} was right: {m1_right_pct:.1f}% ({m1_right_count}/{disagree_count})")
                print(f"    -> {m2} was right: {m2_right_pct:.1f}% ({m2_right_count}/{disagree_count})")
            else:
                print("  Disagreement: 0 cases (Models are identical)")
                
def create_confusion_matrices(df, model_col, output_dir):
    """
    Creates and saves confusion matrix plots for a specific model across all splits.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    splits = df[SPLIT_COL].unique()
    
    print(f"\nGenerating Confusion Matrices for {model_col}...")
    
    for split in splits:
        split_df = df[df[SPLIT_COL] == split]
        y_true = split_df['gt_binary']
        y_pred = split_df[model_col]
        
        # Compute CM
        # 'no' = Low, 'yes' = Bloom
        cm = confusion_matrix(y_true, y_pred, labels=['no', 'yes'])
        
        # Plot
        plt.figure(figsize=(6, 5))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                    xticklabels=['Low', 'Bloom'], 
                    yticklabels=['Low', 'Bloom'])
        
        plt.title(f'{model_col} - {split.upper()}')
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        
        # Save
        filename = f"cm_{model_col}_{split}.png"
        filepath = os.path.join(output_dir, filename)
        plt.savefig(filepath, bbox_inches='tight')
        plt.close()
        print(f"  -> Saved: {filename}")

if __name__ == "__main__":
    analyze_hab_results()